# Generated by Django 6.0.5 on 2026-05-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_note',
            field=models.TextField(blank=True, help_text='برنامه کاری هفتگی منشی', verbose_name='یادداشت برنامه کاری'),
        ),
    ]
